//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.12 at 09:20:55 PM COT 
//


package com.cibertec.edu.pagos;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cibertec.edu.pagos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cibertec.edu.pagos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaPagosRequest }
     * 
     */
    public ListaPagosRequest createListaPagosRequest() {
        return new ListaPagosRequest();
    }

    /**
     * Create an instance of {@link ListaPagosResponse }
     * 
     */
    public ListaPagosResponse createListaPagosResponse() {
        return new ListaPagosResponse();
    }

    /**
     * Create an instance of {@link PagoObject }
     * 
     */
    public PagoObject createPagoObject() {
        return new PagoObject();
    }

    /**
     * Create an instance of {@link CreacionPagoRequest }
     * 
     */
    public CreacionPagoRequest createCreacionPagoRequest() {
        return new CreacionPagoRequest();
    }

    /**
     * Create an instance of {@link CreacionPagoResponse }
     * 
     */
    public CreacionPagoResponse createCreacionPagoResponse() {
        return new CreacionPagoResponse();
    }

    /**
     * Create an instance of {@link RegistroPagoObject }
     * 
     */
    public RegistroPagoObject createRegistroPagoObject() {
        return new RegistroPagoObject();
    }

}
