//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.12 at 09:20:55 PM COT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.edu.cibertec.com/pagos", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cibertec.edu.pagos;
